name: ProsoDeep
theme: jekyll-theme-minimal
# remote_theme: yulijia/freshman21

docs_list_title: ACME Documentation
docs:

- title: Project Home
  url: index.md

- title: ProsoDeep
  url: ProsoDeep.md

- title: Deployment
  url: deployment.html
